#!/bin/sh

cd prj_linux


COMPILE_LINUX=../../../10-Common/include/common_compile_linux.mk

make -f $COMPILE_LINUX TARGET=kdvmedianet LINUX_COMPILER=_RHEL4_ DEBUG=1 ARCH_BITS=32
make -f $COMPILE_LINUX TARGET=kdvmedianet LINUX_COMPILER=_RHEL4_ DEBUG=0 ARCH_BITS=32

cd ..